### ISSUE TITLE
Support target names

### ISSUE THREAD

**Issue by Traap** [Traap/gits#9]
** Snippet: existing**
```yaml
traap:
  - alias: gits
    url: https://github.com/Traap/gits
    do_not_delete: true

  - alias: nvims
    url: https://github.com/Traap/nvims
    do_not_delete: true

  - alias: vimtex
    url: hhttps://github.com/lervag/vimtex
    do_not_delete: true
```

**Snippet:  new concept**
```yaml
traap:
  - repositories:
    - root_dir: directory/to/folder
      # root_dir is optional.  The default is $HOME/group_name
    - alias: gits
      url: https://github.com/Traap/gits
      do_not_delete: true

    - alias: nvims
      url: https://github.com/Traap/nvims
      do_not_delete: true

    - alias: vimtex
      url: hhttps://github.com/lervag/vimtex
      do_not_delete: true
```
